# Generated by Django 4.1.2 on 2022-11-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=60)),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('tipo', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=30)),
                ('zona', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
